name: hyrsm
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud//pytorch
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - ca-certificates=2020.6.20=hecda079_0
  - certifi=2020.6.20=py36h9f0ad1d_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - freetype=2.10.2=he06d7ca_0
  - intel-openmp=2020.1=217
  - jpeg=9d=h516909a_0
  - lcms2=2.11=hbd6801e_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libpng=1.6.37=hed695b0_2
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=hc7e4089_6
  - libwebp-base=1.1.0=h516909a_3
  - lz4-c=1.9.2=he1b5a44_3
  - mkl=2020.1=217
  - mkl-service=2.3.0=py36he904b0f_0
  - mkl_fft=1.1.0=py36h23d657b_0
  - mkl_random=1.1.1=py36h830a2c2_0
  - ncurses=6.2=he6710b0_1
  - ninja=1.10.1=hdb11119_0
  - numpy=1.19.1=py36hbc911f0_0
  - numpy-base=1.19.1=py36hfa32c7d_0
  - olefile=0.46=py_0
  - openssl=1.1.1g=h516909a_1
  - pillow=7.2.0=py36h8328e55_1
  - pip=20.2.2=py36_0
  - python=3.6.10=h7579374_2
  - python_abi=3.6=1_cp36m
  - pytorch=1.5.1=py3.6_cuda10.1.243_cudnn7.6.3_0
  - readline=8.0=h7b6447c_0
  - setuptools=49.6.0=py36_0
  - six=1.15.0=pyh9f0ad1d_0
  - sqlite=3.33.0=h62c20be_0
  - tk=8.6.10=hbc83047_0
  - torchvision=0.6.1=py36_cu101
  - wheel=0.34.2=py36_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h6597ccf_2
  - pip:
    - absl-py==0.10.0
    - aliyun-python-sdk-core==2.13.36
    - aliyun-python-sdk-kms==2.15.0
    - av==8.0.2
    - blessings==1.7
    - cachetools==4.1.1
    - cffi==1.15.0
    - chardet==3.0.4
    - crcmod==1.7
    - cryptography==37.0.2
    - decord==0.4.0
    - einops==0.4.1
    - google-auth==1.20.1
    - google-auth-oauthlib==0.4.1
    - gpustat==0.6.0
    - grpcio==1.31.0
    - idna==2.10
    - importlib-metadata==4.8.3
    - importlib-resources==5.4.0
    - jmespath==0.10.0
    - joblib==1.1.0
    - markdown==3.2.2
    - nvidia-ml-py3==7.352.0
    - oauthlib==3.1.0
    - opencv-python==4.4.0.42
    - oss2==2.15.0
    - pandas==1.1.5
    - protobuf==3.13.0
    - psutil==5.7.2
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.21
    - pycryptodome==3.14.1
    - python-dateutil==2.8.2
    - pytz==2022.1
    - pyyaml==5.3.1
    - requests==2.24.0
    - requests-oauthlib==1.3.0
    - rsa==4.6
    - simplejson==3.17.2
    - tensorboard==2.3.0
    - tensorboard-plugin-wit==1.7.0
    - tqdm==4.64.0
    - typing-extensions==4.1.1
    - urllib3==1.25.10
    - werkzeug==1.0.1
    - zipp==3.6.0
