_BASE: ../OTAM_base.yaml
TASK_TYPE: few_shot_action
RANDOM_SEED: 18
TRAIN:
  ENABLE: true
  USE_CLASSIFICATION: true
  USE_LOCAL: true
  USE_CLASSIFICATION_VALUE: 0.15
  NUM_CLASS: 31
  POSITION_A: 50
  POSITION_B: 1.
  DATASET_FEW: HMDB_few_shot
  DATASET: Ssv2_few_shot
  META_BATCH: true  # meta or not
  NUM_SAMPLES: 1000000
  WINDOW_SIZE: 1
  TEMPORAL_WEIGHT: 0.5
  TEMPORAL_LOSS_WEIGHT: 0.2
  TEMPORAL_BALANCE: 51.0
  BALANCE_COEFFICIENT: 20
  WAY: 5
  SHOT: 2
  QUERY_PER_CLASS: 6
  QUERY_PER_CLASS_TEST: 1
  NUM_TRAIN_TASKS: 2000
  NUM_TEST_TASKS: 10000
  VAL_FRE_ITER: 100
  BATCH_SIZE: 4  # Same with NUM_GPUS
  BATCH_SIZE_PER_TASK: 4
  CHECKPOINT_FILE_PATH: ""
  EVAL_PERIOD: 2
  NUM_FOLDS: 1

AUGMENTATION:
  COLOR_AUG: false
  NO_RANDOM_ERASE: false
  SUPPORT_QUERY_DIFF: true

TEST:
  ENABLE: false
  DATASET: Ssv2_few_shot
  BATCH_SIZE: 4  # Same with NUM_GPUS
  TEST_SET: val
  NUM_ENSEMBLE_VIEWS: 1
  SPATIAL_CROPS: cctltr
  AUTOMATIC_MULTI_SCALE_TEST: false
  UPLOAD_CLASSIFIER_RESULTS: true

DATA:
  DATA_ROOT_DIR: /mnt/workspace/hmdb51/  
  ANNO_DIR: ./configs/projects/hyrsmplusplus/hmdb51/
  NUM_INPUT_FRAMES: 8
  SAMPLING_RATE: 50 # 50
  # SAMPLING_RATE_TRAIN: 3
  SAMPLING_UNIFORM: false
  TRAIN_JITTER_SCALES: [256, 256]
  TRAIN_CROP_SIZE: 224 # 84  # 224
  TEST_CROP_SIZE: 224
  TEST_SCALE: 256
  TEST_CENTER_CROP: true
  CLIP_INTERVAL: 8
  FPS: 12
  TARGET_FPS: 12


LOG_PERIOD: 50
SOLVER:
  BASE_LR: 0.00005  # 0.0001 # 0.0005
  LR_POLICY: steps_with_relative_lrs
  STEPS_ITER: 300
  STEPS: [0, 2, 3, 7]
  LRS: [1, 0.5, 0.1, 0.01]
  MAX_EPOCH: 10
  MOMENTUM: 0.9
  WEIGHT_DECAY: 5e-4
  WARMUP_EPOCHS: 1
  WARMUP_START_LR: 0.00001
  OPTIM_METHOD: adam
  DAMPENING: 0.0
  NESTEROV: true
# add bn, use same lr settings as server

VIDEO:
  HEAD:
    NAME: CNN_HyRSM_plusplus_5shot  
    BACKBONE_NAME: "resnet50"
    
  BACKBONE:
    META_ARCH: Identity

NUM_GPUS: 4
OUTPUT_DIR: output/HyRSMplusplus_HMDB51_2shot



