_BASE: ../OTAM_base.yaml
TASK_TYPE: few_shot_action
TRAIN:
  ENABLE: true
  USE_CLASSIFICATION: true
  USE_CLASSIFICATION_VALUE: 1.5
  DATASET_FEW: HMDB_few_shot
  DATASET: Ssv2_few_shot
  META_BATCH: true  # meta or not
  NUM_SAMPLES: 1000000
  WAY: 5
  SHOT: 1
  QUERY_PER_CLASS: 5
  QUERY_PER_CLASS_TEST: 1
  NUM_TRAIN_TASKS: 3000
  NUM_TEST_TASKS: 10000
  VAL_FRE_ITER: 100
  CLASS_NAME: ['Apply Eye Makeup', 'Archery', 'Baby Crawling', 'Balance Beam', 'Band Marching', 'Baseball Pitch', 'Basketball', 'Basketball Dunk', 'Bench Press', 'Biking', 'Billiards', 'Blow DryHair', 'Body Weight Squats', 'Bowling', 'Boxing Punching Bag', 'Boxing Speed Bag', 'Breast Stroke', 'Brushing Teeth', 'Cricket Bowling', 'Drumming', 'Fencing', 'Field Hockey Penalty', 'Frisbee Catch', 'Front Crawl', 'Haircut', 'Hammering', 'Head Massage', 'Hula Hoop', 'Javelin Throw', 'Juggling Balls', 'Jumping Jack', 'Kayaking', 'Knitting', 'Long Jump', 'Lunges', 'Military Parade', 'Mixing', 'Mopping Floor', 'Nunchucks', 'Parallel Bars', 'Pizza Tossing', 'Playing Cello', 'Playing Dhol', 'Playing Flute', 'Playing Piano', 'Playing Sitar', 'Playing Tabla', 'Playing Violin', 'Pole Vault', 'Pull Ups', 'Push Ups', 'Rafting', 'Rope Climbing', 'Rowing', 'Shaving Beard', 'Skijet', 'Soccer Juggling', 'Soccer Penalty', 'Sumo Wrestling', 'Swing', 'Table Tennis Shot', 'Tai Chi', 'Throw Discus', 'Trampoline Jumping', 'Typing', 'Uneven Bars', 'Walking WithDog', 'Wall Pushups', 'Writing On Board', 'Yo Yo']
  BATCH_SIZE: 4  # Same with NUM_GPUS
  BATCH_SIZE_PER_TASK: 4  
  CHECKPOINT_FILE_PATH: ""
  EVAL_PERIOD: 2
  NUM_FOLDS: 1

AUGMENTATION:
  COLOR_AUG: false
  NO_RANDOM_ERASE: true
  

TEST:
  ENABLE: false
  DATASET: Ssv2_few_shot
  CLASS_NAME: ['Blowing Candles', 'Clean And Jerk', 'Cliff Diving', 'Cutting in Kitchen', 'Diving', 'Floor Gymnastics', 'Golf Swing', 'Handstand Walking', 'Horse Race', 'Ice Dancing', 'Jump Rope', 'Pommel Horse', 'Punch', 'Rock Climbing Indoor', 'Salsa Spin', 'Skiing', 'Sky Diving', 'Still Rings', 'Surfing', 'Tennis Swing', 'Volleyball Spiking']
  BATCH_SIZE: 4  # Same with NUM_GPUS
  TEST_SET: val
  NUM_ENSEMBLE_VIEWS: 1
  SPATIAL_CROPS: cctltr
  AUTOMATIC_MULTI_SCALE_TEST: false
  UPLOAD_CLASSIFIER_RESULTS: true

DATA:
  DATA_ROOT_DIR: /mnt/workspace/ucf101/  
  ANNO_DIR: ./configs/projects/CLIPFSAR/ucf101/
  NUM_INPUT_FRAMES: 8
  SAMPLING_RATE: 50 # 50
  # SAMPLING_RATE_TRAIN: 3
  SAMPLING_UNIFORM: false
  TRAIN_JITTER_SCALES: [256, 256]
  MEAN: [0.48145466, 0.4578275, 0.40821073]
  STD: [0.26862954, 0.26130258, 0.27577711]
  TRAIN_CROP_SIZE: 224 # 84  # 224
  TEST_CROP_SIZE: 224
  TEST_SCALE: 256
  TEST_CENTER_CROP: true
  CLIP_INTERVAL: 8
  FPS: 12
  TARGET_FPS: 12

LOG_PERIOD: 50
SOLVER:
  BASE_LR: 0.000002
  LR_POLICY: steps_with_relative_lrs
  STEPS_ITER: 600
  STEPS: [0, 4, 6]
  LRS: [1, 0.1, 0.01]
  MAX_EPOCH: 10
  MOMENTUM: 0.9
  WEIGHT_DECAY: 5e-5
  WARMUP_EPOCHS: 1
  WARMUP_START_LR: 0.0000001
  OPTIM_METHOD: adam
  DAMPENING: 0.0
  NESTEROV: true
# add bn, use same lr settings as server

VIDEO:
  HEAD:
    NAME: CNN_OTAM_CLIPFSAR
    BACKBONE_NAME: "RN50"
  
  BACKBONE:
    META_ARCH: Identity


NUM_GPUS: 4
OUTPUT_DIR: output/CLIPFSAR_UCF101_1shot


