_BASE: ../OTAM_base.yaml
TASK_TYPE: few_shot_action
TRAIN:
  ENABLE: true
  USE_CLASSIFICATION: true
  USE_CLASSIFICATION_VALUE: 3.0
  DATASET: Ssv2_few_shot
  META_BATCH: true  # meta or not
  NUM_SAMPLES: 1000000
  WAY: 5
  SHOT: 1
  SHOT_TEST: 5
  QUERY_PER_CLASS: 5
  MERGE_BEFORE: true
  QUERY_PER_CLASS_TEST: 1
  NUM_TRAIN_TASKS: 30000
  NUM_TEST_TASKS: 10000
  VAL_FRE_ITER: 1000
  BATCH_SIZE: 4  # Same with NUM_GPUS
  CLASS_NAME: ['Bending [something] until it breaks', 'Closing [something]', 'Covering [something] with [something]', 'Dropping [something] behind [something]', 'Dropping [something] in front of [something]', 'Dropping [something] into [something]', 'Folding [something]', 'Holding [something]', 'Holding [something] next to [something]', 'Letting [something] roll along a flat surface', 'Letting [something] roll down a slanted surface', 'Lifting a surface with [something] on it but not enough for it to slide down', 'Lifting [something] with [something] on it', 'Moving away from [something] with your camera', 'Moving [something] across a surface until it falls down', 'Moving [something] and [something] closer to each other', 'Moving [something] and [something] so they collide with each other', 'Moving [something] down', 'Moving [something] up', 'Plugging [something] into [something]', 'Poking a hole into [something soft]', "Poking [something] so lightly that it doesn't or almost doesn't move", 'Poking [something] so that it falls over', 'Pouring [something] into [something]', 'Pouring [something] into [something] until it overflows', 'Pouring [something] onto [something]', 'Pretending to be tearing [something that is not tearable]', 'Pretending to close [something] without actually closing it', 'Pretending to pick [something] up', 'Pretending to put [something] next to [something]', 'Pretending to spread air onto [something]', 'Pretending to take [something] out of [something]', 'Pulling [something] onto [something]', 'Pulling two ends of [something] so that it gets stretched', 'Pulling two ends of [something] so that it separates into two pieces', 'Pushing [something] from left to right', 'Pushing [something] off of [something]', 'Pushing [something] so that it falls off the table', 'Pushing [something] so that it slightly moves', 'Putting [number of] [something] onto [something]', 'Putting [something] and [something] on the table', "Putting [something] onto a slanted surface but it doesn't glide down", 'Putting [something] onto [something]', 'Putting [something similar to other things that are already on the table]', 'Showing a photo of [something] to the camera', 'Showing [something] behind [something]', '[Something] colliding with [something] and both are being deflected', 'Spilling [something] next to [something]', 'Spilling [something] onto [something]', 'Spinning [something] that quickly stops spinning', 'Spreading [something] onto [something]', 'Squeezing [something]', 'Stuffing [something] into [something]', 'Taking [something] from [somewhere]', 'Tearing [something] into two pieces', "Tilting [something] with [something] on it slightly so it doesn't fall down", 'Tilting [something] with [something] on it until it falls off', 'Tipping [something] with [something in it] over, so [something in it] falls out', 'Turning the camera downwards while filming [something]', 'Turning the camera left while filming [something]', 'Turning the camera upwards while filming [something]', 'Twisting (wringing) [something] wet until water comes out', 'Twisting [something]', 'Uncovering [something]']
  BATCH_SIZE_PER_TASK: 4
  CHECKPOINT_FILE_PATH: ""
  EVAL_PERIOD: 2
  NUM_FOLDS: 1

AUGMENTATION:
  COLOR_AUG: false
  NO_RANDOM_ERASE: true

TEST:
  ENABLE: false
  DATASET: Ssv2_few_shot
  BATCH_SIZE: 4  # Same with NUM_GPUS
  TEST_SET: val
  CLASS_NAME: ['Approaching [something] with your camera', 'Digging [something] out of [something]', 'Dropping [something] next to [something]', 'Dropping [something] onto [something]', 'Failing to put [something] into [something] because [something] does not fit', 'Lifting up one end of [something] without letting it drop down', 'Picking [something] up', 'Poking a stack of [something] without the stack collapsing', 'Pouring [something] out of [something]', 'Pretending to open [something] without actually opening it', 'Pretending to put [something] behind [something]', 'Pretending to put [something] into [something]', 'Pretending to put [something] underneath [something]', 'Pretending to sprinkle air onto [something]', 'Pulling [something] from left to right', 'Pulling [something] out of [something]', 'Pushing [something] from right to left', 'Removing [something], revealing [something] behind', 'Showing [something] next to [something]', 'Showing that [something] is empty', 'Spilling [something] behind [something]', 'Taking [something] out of [something]', 'Throwing [something] in the air and letting it fall', 'Tipping [something] over']
  NUM_ENSEMBLE_VIEWS: 1
  SPATIAL_CROPS: cctltr
  AUTOMATIC_MULTI_SCALE_TEST: false
  UPLOAD_CLASSIFIER_RESULTS: true

DATA:
  DATA_ROOT_DIR: /mnt/workspace/SSv2/  
  ANNO_DIR: ./configs/projects/CLIPFSAR/ssv2_full/
  NUM_INPUT_FRAMES: 8
  SAMPLING_RATE: 50
  SAMPLING_UNIFORM: false
  TRAIN_JITTER_SCALES: [256, 256]
  TRAIN_CROP_SIZE: 224 # 84  # 224
  TEST_CROP_SIZE: 224
  MEAN: [0.48145466, 0.4578275, 0.40821073]
  STD: [0.26862954, 0.26130258, 0.27577711]
  TEST_SCALE: 256
  TEST_CENTER_CROP: true
  CLIP_INTERVAL: 8
  FPS: 12
  TARGET_FPS: 12

LOG_PERIOD: 50
SOLVER:
  BASE_LR: 0.00005 
  LR_POLICY: steps_with_relative_lrs
  STEPS_ITER: 4000
  STEPS: [0, 4, 6]
  LRS: [1, 0.1, 0.01]
  MAX_EPOCH: 10
  MOMENTUM: 0.9
  WEIGHT_DECAY: 5e-5
  WARMUP_EPOCHS: 1
  WARMUP_START_LR: 0.00001
  OPTIM_METHOD: adam
  DAMPENING: 0.0
  NESTEROV: true
# add bn, use same lr settings as server

VIDEO:
  HEAD:
    NAME: CNN_OTAM_CLIPFSAR  
    BACKBONE_NAME: "RN50"

  BACKBONE:
    META_ARCH: Identity

NUM_GPUS: 4
OUTPUT_DIR: output/CLIPFSAR_SSv2_Full_5shot


