_BASE: ../OTAM_base.yaml
TASK_TYPE: few_shot_action
RANDOM_SEED: 18
TRAIN:
  ENABLE: true
  USE_CLASSIFICATION: true
  USE_CLASSIFICATION_VALUE: 0.5
  POSITION_A: 2048
  POSITION_B: 0.1
  USE_LOCAL: true
  NUM_CLASS: 60
  DATASET: Ssv2_few_shot
  DATASET_FEW: Kinetics_few_shot
  WINDOW_SIZE: 3
  TEMPORAL_WEIGHT: 0.5
  TEMPORAL_LOSS_WEIGHT:  0.1
  TEMPORAL_BALANCE: 23.0
  BALANCE_COEFFICIENT: 10
  META_BATCH: true  # meta or not
  NUM_SAMPLES: 1000000
  WAY: 5
  SHOT: 4
  QUERY_PER_CLASS: 4  # 7
  QUERY_PER_CLASS_TEST: 1
  NUM_TRAIN_TASKS: 2000
  NUM_TEST_TASKS: 10000
  VAL_FRE_ITER: 100
  BATCH_SIZE: 4  # Same with NUM_GPUS
  BATCH_SIZE_PER_TASK: 4
  CHECKPOINT_FILE_PATH: ""
  EVAL_PERIOD: 2
  NUM_FOLDS: 1

AUGMENTATION:
  COLOR_AUG: false
  NO_RANDOM_ERASE: true
  SUPPORT_QUERY_DIFF: true

TEST:
  ENABLE: false
  DATASET: Ssv2_few_shot
  BATCH_SIZE: 4  # Same with NUM_GPUS
  TEST_SET: val
  NUM_ENSEMBLE_VIEWS: 1
  SPATIAL_CROPS: cctltr
  AUTOMATIC_MULTI_SCALE_TEST: false
  UPLOAD_CLASSIFIER_RESULTS: true

DATA:
  DATA_ROOT_DIR: /mnt/workspace/epic_kitchens/
  ANNO_DIR: ./configs/projects/hyrsmplusplus/epic_kitchens/
  NUM_INPUT_FRAMES: 8
  SAMPLING_RATE: 50
  SAMPLING_UNIFORM: false
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224 # 84  # 224
  TEST_CROP_SIZE: 224
  TEST_SCALE: [256, 320]
  TEST_CENTER_CROP: true
  CLIP_INTERVAL: 8
  FPS: 12
  TARGET_FPS: 12

LOG_PERIOD: 50
SOLVER:
  BASE_LR: 0.00005  # 0.00002--> 67.4 
  LR_POLICY: steps_with_relative_lrs
  STEPS_ITER: 400
  STEPS: [0, 4, 7]
  LRS: [1, 0.1, 0.01]
  MAX_EPOCH: 10
  MOMENTUM: 0.9
  WEIGHT_DECAY: 5e-5   # 3e-5 --> 67.4
  WARMUP_EPOCHS: 1
  WARMUP_START_LR: 0.00001
  OPTIM_METHOD: adam
  DAMPENING: 0.0
  NESTEROV: true
# add bn, use same lr settings as server

VIDEO:
  HEAD:
    NAME: CNN_HyRSM_plusplus_5shot  # or CNN_HyRSM_plusplus_5shot
    BACKBONE_NAME: "resnet50"

  BACKBONE:
    META_ARCH: Identity

NUM_GPUS: 4
OUTPUT_DIR: output/HyRSMplusplus_Epic_4shot 